server:
  port: 8091
spring:
  main:
    allow-bean-definition-overriding: true
levensverzekering-service:
  host: localhost
  port: 8090
stubrunner:
  ids: 'nl.bank:levensverzekering-service:+:stubs:8090'
  repositoryRoot: https://repo.spring.io/libs-snapshot
logging:
  level:
    root: INFO
    nl.bank.levensverzekeringservice: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG